databases:
  - name: Explore_GUNMA_DB
    databaseName: explore_gunma_db
    user: Renderで作成したRailsのアプリ名
    region: singapore

services:
  - type: web
    name: Explore_GUNMA
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Explore_GUNMA_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

